name: read_right_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  record: ^6.1.2
  just_audio: ^0.10.5
  audio_session: ^0.1.25
  path_provider: ^2.1.5
  speech_to_text: ^7.3.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/seed_words.csv
